# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recorrido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Marcador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=30)),
                ('mapa', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='recorrido.Mapa')),
            ],
        ),
        migrations.RenameModel(
            old_name='Parada',
            new_name='Coordenada',
        ),
        migrations.DeleteModel(
            name='PuntoDeCarga',
        ),
        migrations.RenameField(
            model_name='recorrido',
            old_name='numero_linea',
            new_name='ancho',
        ),
        migrations.RenameField(
            model_name='recorrido',
            old_name='ruta',
            new_name='cordenada',
        ),
        migrations.AddField(
            model_name='recorrido',
            name='nombre',
            field=models.CharField(default='linea', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marcador',
            name='posicion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recorrido.Coordenada'),
        ),
        migrations.AddField(
            model_name='mapa',
            name='posicion_inicial',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recorrido.Coordenada'),
        ),
        migrations.AddField(
            model_name='recorrido',
            name='mapa',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='recorrido.Mapa'),
        ),
    ]
